/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modcapture;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 107310
 */
public class Details extends javax.swing.JFrame {

    boolean live = true;
    String nomeProcesso = "";
    int channel;
    String dir = "";
    Interfaccia intf;
    Application app;

    /**
     * Creates new form Details
     */
    class Refresh extends Thread {

        @Override
        public void run() {
            while (live) {
                ImageIcon image = new ImageIcon(dir + channel + "\\LIVE\\live.jpg");
                Image img1 = image.getImage();
                Image img2 = img1.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon i = new ImageIcon(img2);
                jLabel1.setIcon(i);
                System.out.println("entrato refresh");
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                    System.out.println(ex);
                }
            }
        }
    }

    public Details(String[] args, int source, String nome, String directory, Interfaccia in) {
        initComponents();
        nomeProcesso = nome;
        channel = source;
        dir = directory;
        intf=in;
        app=Interfaccia.getApp(nomeProcesso);
        if (app.isLive()) {
            livebutton.setEnabled( false );
            if (app.isRecording()) {
                recbutton.setEnabled(false);
                }
            else stopbutton.setEnabled(false);
            }
        else {
            pausebutton.setEnabled (false);
            recbutton.setEnabled(false);
            stopbutton.setEnabled(false);
        }
        
        
        ImageIcon image = new ImageIcon("C:\\Users\\107310\\Desktop\\imm\\test.jpg");
        System.out.println(args[2]);
        Image img1 = image.getImage();
        Image img2 = img1.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        jTextField1.setText(args[0]);
        jTextField2.setText(args[1]);
        jTextField3.setText(args[2]);
        LabelRes.setText(args[3]);
        jLabel1.setIcon(i);
        LabelStato.setText(args[4]);
        System.out.println(nomeProcesso);

        Refresh a = new Refresh();
        //a.run();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        LabelStato = new javax.swing.JLabel();
        LabelRes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        livebutton = new javax.swing.JButton();
        pausebutton = new javax.swing.JButton();
        recbutton = new javax.swing.JButton();
        stopbutton = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Finestra Dettagli");

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Nome Sorgente:");

        jLabel4.setText("Qualità %");

        jLabel5.setText("FPS");

        jLabel6.setText("Risoluzione");

        jLabel7.setText("Stato");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "800x600", "1000x800", "1200x1000", "1400x1200" }));

        LabelStato.setText("jLabel8");

        LabelRes.setText("jLabel8");

        jButton1.setText("Salva Valori");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(LabelRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelStato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LabelRes))
                .addGap(5, 5, 5)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LabelStato))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        livebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\107310\\Documents\\NetBeansProjects\\modcapture\\src\\resources\\play.png")); // NOI18N
        livebutton.setText("LIVE");
        livebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livebuttonActionPerformed(evt);
            }
        });

        pausebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\107310\\Documents\\NetBeansProjects\\modcapture\\src\\resources\\pause.png")); // NOI18N
        pausebutton.setText("PAUSA LIVE");
        pausebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausebuttonActionPerformed(evt);
            }
        });

        recbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\107310\\Documents\\NetBeansProjects\\modcapture\\src\\resources\\rec.png")); // NOI18N
        recbutton.setText("REGISTRA");
        recbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recbuttonActionPerformed(evt);
            }
        });

        stopbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\107310\\Documents\\NetBeansProjects\\modcapture\\src\\resources\\stop.png")); // NOI18N
        stopbutton.setText("STOP REGISTRA");
        stopbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(livebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pausebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopbutton)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(livebutton)
                    .addComponent(pausebutton)
                    .addComponent(recbutton)
                    .addComponent(stopbutton))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean checked = true;
        String[] newValues = new String[5];
        //System.arraycopy(args,0, newValues, 0, 8);
        newValues[0] = jTextField1.getText();
        newValues[1] = jTextField2.getText();
        int sup = 0;
        try {
            int num = Integer.parseInt(newValues[1]);   // is an integer!  
            sup = num;
        } catch (NumberFormatException e) {
            checked = false;
            JOptionPane.showMessageDialog(null, "Il valore per Qualità non è un numero! ");    // not an integer!
        }
        if (sup < 1 || sup > 100) {
            JOptionPane.showMessageDialog(null, "Il valore per Qualità deve essere compreso tra 1 e 100! ");
            checked = false;
        }
        sup = 0;
        newValues[2] = jTextField3.getText();
        try {
            int num = Integer.parseInt(newValues[2]);   // is an integer! 
            sup = num;
        } catch (NumberFormatException e) {
            checked = false;
            JOptionPane.showMessageDialog(null, "Il valore per FPS non è un numero");    // not an integer!
        }
        if (sup < 1 || sup > 10) {
            JOptionPane.showMessageDialog(null, "Il valore per FPS deve essere compreso tra 1 e 10! ");
            checked = false;
        }
        sup = jComboBox1.getSelectedIndex();
        switch (sup) {
            case 0:
                JOptionPane.showMessageDialog(null, "Selezionato 800x600 ");
                newValues[3] = "800";
                newValues[4] = "600";
                System.out.println(newValues[4]);
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Selezionato 1000x800 ");
                newValues[3] = "1000";
                newValues[4] = "800";
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Selezionato 1200x1000 ");
                newValues[3] = "1200";
                newValues[4] = "1000";
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Selezionato 1400x1200 ");
                newValues[3] = "1400";
                newValues[4] = "1200";
                break;
        }
    if (checked) { 
        Detailschange u=new Detailschange(newValues,nomeProcesso,channel,intf,this);
        u.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void livebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livebuttonActionPerformed
        app.turnOnLive();
        intf.updateStato(channel, app);
        
        pausebutton.setEnabled(true);
        livebutton.setEnabled(false);
        //try {
         //   Thread.sleep(1500);
       // }
        //catch (InterruptedException ex) { 
        //                System.out.println(ex);
        //}
        LabelStato.setText(app.getStato());
    }//GEN-LAST:event_livebuttonActionPerformed

    private void pausebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausebuttonActionPerformed
        app.turnOffLive();
        intf.updateStato(channel, app);
        
        pausebutton.setEnabled(false);
        livebutton.setEnabled(true);
    
        LabelStato.setText(app.getStato());
    }//GEN-LAST:event_pausebuttonActionPerformed

    private void recbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recbuttonActionPerformed
        app.turnOnRec();
        stopbutton.setEnabled(true);
        recbutton.setEnabled(false);
     
        LabelStato.setText(app.getStato());
    }//GEN-LAST:event_recbuttonActionPerformed

    private void stopbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbuttonActionPerformed
        app.turnOffRec();
        recbutton.setEnabled(true);
        stopbutton.setEnabled(false);
        
        LabelStato.setText(app.getStato());
    }//GEN-LAST:event_stopbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                //  this.add(new JLabel(new ImageIcon("Path/To/Your/Image.png")));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelRes;
    private javax.swing.JLabel LabelStato;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton livebutton;
    private javax.swing.JButton pausebutton;
    private javax.swing.JButton recbutton;
    private javax.swing.JButton stopbutton;
    // End of variables declaration//GEN-END:variables
}
