/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modcapture;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;

/**
 *
 * @author 107310
 */
public class Detailschange extends javax.swing.JFrame {
    String[] newValues = new String[5];
    String processo="";
    int source;
    Interfaccia intf;
    Details detail;
    /**
     * Creates new form Detailschange
     */
    
    public void writeFile2() throws IOException {
        FileWriter fw=new FileWriter("C:\\Users\\107310\\Documents\\NetBeansProjects\\modcapture\\src\\main\\java\\modcapture\\Config.txt");

 
	for (int i = 0; i < 10; i++) {
		fw.write("something");
	}
 
	fw.close();
}
    
    
    public Detailschange(String[] args, String proces, int num, Interfaccia in, Details det) {
        newValues=args;
        System.out.println("nomeprocesso");
        System.out.println(proces);
        detail=det;
        processo=proces;
        source=num;
        intf=in;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Attenzione!");

        jLabel2.setText("I valori per questa sorgente verranno sovrascritti con i valori inseriti.");

        jLabel3.setText("Si è sicuri di voler continuare?");

        jButton1.setText("Si, modificali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("No, annulla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       setVisible(false); //you can't see me!
       dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
           BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\107310\\Documents\\NetBeansProjects\\modcapture\\src\\main\\java\\modcapture\\Config.txt"));
           String oldContent = "";
          String line = reader.readLine();
          int i=0;
          int count=0;
          String[] args = new String [8];

        while (line != null)
            {
            if (source>=0) {
                
                if (i<source*10+2) {
                    oldContent = oldContent + line + System.lineSeparator();
                    args[count]=line;
                    count++;
                }
                else if(i<source*10+6) {
                    oldContent = oldContent + newValues[(i%10)-1] + System.lineSeparator();
                    args[count]=newValues[(i%10)-1];
                    count++;
                }
                else if(i==source*10+6){
                    oldContent = oldContent + newValues[0] + System.lineSeparator();
                    args[count]=newValues[0];
                    source=-1;
                }
                
            }
            else { oldContent = oldContent + line + System.lineSeparator();};
            line = reader.readLine();
            
            i++;
            }
          //  System.out.println(oldContent);
              System.out.println(args);
           FileWriter fw=new FileWriter("C:\\Users\\107310\\Documents\\NetBeansProjects\\modcapture\\src\\main\\java\\modcapture\\Config.txt");
           fw.write(oldContent);
          
        reader.close();
	fw.close();
        
        intf.changedValues(processo, args);
        dispose();
        detail.dispose();
        }
        catch (IOException ex) {System.out.println(ex);}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
